"use client";

import { useMemo } from "react";
import { useKimbotStore } from "@/app/store/kimbotStore";
import { useGrcBotStore } from "@/app/store/grcBotStore";
import { useRiskStore } from "@/app/store/riskStore";

const BUDGET_MONTHLY_USD = 20;
const ACTIVE_TENANTS_MAX = 100;

/** Cost per raw signal generated by KIMBOT (simulated compute) */
const COST_PER_SIGNAL_USD = 0.02;
/** Cost per active tenant/month for GRCBOT-managed companies */
const COST_PER_TENANT_USD = 0.08;
/** When GRCBOT is at 100 companies, burn multiplier to accelerate and test billing alerts */
const SCALE_AT_100_MULTIPLIER = 2.5;
/** Projected revenue per tenant/month for margin estimate */
const REVENUE_PER_TENANT_USD = 55;

export type ComputeBilling = {
  /** Active tenants (GRCBOT company count when on, else 1 for base) */
  activeTenants: number;
  activeTenantsMax: number;
  /** Current month burn in USD from simulation */
  monthlyBurnUsd: number;
  budgetMonthlyUsd: number;
  /** 0–100+ (can exceed 100 when over budget) */
  burnPct: number;
  /** Projected revenue from active tenants */
  projectedRevenueUsd: number;
  /** projectedRevenueUsd - monthlyBurnUsd */
  marginEstimateUsd: number;
  totalKimbotSignals: number;
  /** Pipeline threats with id starting with grcbot- */
  grcBotRisksCount: number;
  /** True when GRCBOT is at 100 companies (burn accelerates) */
  burnAccelerated: boolean;
};

export function useComputeBilling(): ComputeBilling {
  const totalSignalsGenerated = useKimbotStore((s) => s.totalSignalsGenerated);
  const grcBotEnabled = useGrcBotStore((s) => s.enabled);
  const grcBotCompanyCount = useGrcBotStore((s) => s.companyCount);
  const pipelineThreats = useRiskStore((s) => s.pipelineThreats);

  return useMemo(() => {
    const activeTenants = grcBotEnabled ? grcBotCompanyCount : 1;
    const grcBotRisksCount = pipelineThreats.filter((t) => t.id.startsWith("grcbot-")).length;

    const signalCost = totalSignalsGenerated * COST_PER_SIGNAL_USD;
    const tenantCostBase = activeTenants * COST_PER_TENANT_USD;
    const burnAccelerated = grcBotEnabled && grcBotCompanyCount >= ACTIVE_TENANTS_MAX;
    const tenantMultiplier = burnAccelerated ? SCALE_AT_100_MULTIPLIER : 1;
    const tenantCost = tenantCostBase * tenantMultiplier;
    const monthlyBurnUsd = signalCost + tenantCost;

    const burnPct = BUDGET_MONTHLY_USD > 0 ? (monthlyBurnUsd / BUDGET_MONTHLY_USD) * 100 : 0;
    const projectedRevenueUsd = activeTenants * REVENUE_PER_TENANT_USD;
    const marginEstimateUsd = projectedRevenueUsd - monthlyBurnUsd;

    return {
      activeTenants,
      activeTenantsMax: ACTIVE_TENANTS_MAX,
      monthlyBurnUsd,
      budgetMonthlyUsd: BUDGET_MONTHLY_USD,
      burnPct,
      projectedRevenueUsd,
      marginEstimateUsd,
      totalKimbotSignals: totalSignalsGenerated,
      grcBotRisksCount,
      burnAccelerated,
    };
  }, [
    totalSignalsGenerated,
    grcBotEnabled,
    grcBotCompanyCount,
    pipelineThreats,
  ]);
}
