import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./components/AppShell";
import DebugPanel from "./components/dev/DebugPanel";
import { TenantProvider } from "./context/TenantProvider";
import GlobalDropZone from "./components/GlobalDropZone";
import IronwaveDMZTelemetryHost from "./components/IronwaveDMZTelemetryHost";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen overflow-hidden antialiased font-sans`}
      >
        <TenantProvider>
          <IronwaveDMZTelemetryHost />
          <GlobalDropZone />
          <AppShell>{children}</AppShell>
          <DebugPanel />
          {/* SpeedInsights disabled: can trigger async Client Component error in Next 16/Turbopack */}
        </TenantProvider>
      </body>
    </html>
  );
}
