import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./components/AppShell";
import IronguardBootstrap from "./components/IronguardBootstrap";
import { TenantProvider } from "./context/TenantProvider";
import { ConstitutionalIntegrityProvider } from "./context/ConstitutionalIntegrityProvider";
import GlobalDropZone from "./components/GlobalDropZone";
import EmergencyOverlay from "./components/EmergencyOverlay";
import ConstitutionalDegradedBanner from "./components/ConstitutionalDegradedBanner";
import StaleDataLockdownBanner from "./components/StaleDataLockdownBanner";
import GlobalEkgPortal from "./components/GlobalEkgPortal";
import NotificationOverlay from "./components/NotificationOverlay";
import AuditTrackingProvider from "./providers/AuditTrackingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full font-sans" suppressHydrationWarning>
      {/* suppressHydrationWarning: Prevents crashes from browser extensions (Grammarly, etc.) injecting attributes into the DOM. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden antialiased font-sans`}
        suppressHydrationWarning
      >
        <TenantProvider>
          <GlobalEkgPortal />
          <NotificationOverlay />
          <ConstitutionalIntegrityProvider>
            <AuditTrackingProvider>
            <div className="flex h-screen w-screen flex-col overflow-hidden bg-slate-950">
              <main className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
                <EmergencyOverlay />
                <ConstitutionalDegradedBanner />
                <StaleDataLockdownBanner />
                <IronguardBootstrap />
                <GlobalDropZone />
                <AppShell>{children}</AppShell>
                {/* SpeedInsights disabled: can trigger async Client Component error in Next 16/Turbopack */}
              </main>
            </div>
            </AuditTrackingProvider>
          </ConstitutionalIntegrityProvider>
        </TenantProvider>
      </body>
    </html>
  );
}
