import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
  Link,
  Tailwind,
} from "@react-email/components";
import * as React from "react";

interface UrgentThreatEmailProps {
  tenantName: string;
  riskId: string;
  summary: string;
  priority: string;
}

export const UrgentThreatEmail = ({
  tenantName,
  riskId,
  summary,
  priority,
}: UrgentThreatEmailProps) => (
  <Html>
    <Head />
    <Preview>URGENT: Security Threat Quarantined for {tenantName}</Preview>
    <Tailwind>
      <Body className="bg-slate-50 my-auto mx-auto font-sans">
        <Container className="border border-solid border-slate-200 rounded my-[40px] mx-auto p-[20px] w-[465px] bg-white">
          <Section className="mt-[32px]">
            <Text className="text-red-600 text-[12px] font-bold tracking-widest uppercase text-center">
              Priority: {priority}
            </Text>
          </Section>
          <Heading className="text-slate-900 text-[24px] font-normal text-center p-0 my-[30px] mx-0">
            <strong>Ironlock</strong> Security Alert
          </Heading>
          <Text className="text-slate-700 text-[14px] leading-[24px]">
            The Ironframe workforce has identified and quarantined a critical threat for{" "}
            <strong>{tenantName}</strong>.
          </Text>
          <Section className="bg-slate-100 rounded p-[15px] my-[20px]">
            <Text className="text-slate-500 text-[12px] uppercase font-bold mb-[5px]">Risk ID</Text>
            <Text className="text-slate-900 font-mono text-[14px] mt-0 mb-[10px]">{riskId}</Text>

            <Text className="text-slate-500 text-[12px] uppercase font-bold mb-[5px]">Summary</Text>
            <Text className="text-slate-700 text-[14px] mt-0">{summary}</Text>
          </Section>
          <Section className="text-center mt-[32px] mb-[32px]">
            <Link
              className="bg-red-600 rounded text-white text-[12px] font-semibold no-underline text-center px-5 py-3"
              href={`https://ironframe.ai/dashboard/risks/${riskId}`}
            >
              Review in Dashboard
            </Link>
          </Section>
          <Hr className="border border-solid border-slate-200 my-[26px] mx-0 w-full" />
          <Text className="text-slate-400 text-[12px] leading-[24px]">
            This alert was automatically generated by the Ironframe Integrity Hub. No manual
            intervention was required for initial quarantine.
          </Text>
        </Container>
      </Body>
    </Tailwind>
  </Html>
);

export default UrgentThreatEmail;
